version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: plouf_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plouf_backend
    #Enable the port 8000 bind for backend debugging or API access
    #ports:
    # - "8000:8000"
    environment:
      MONGO_ADDRESS: mongodb:27017
      MONGO_DATABASE: pool_database
      MONGO_COLLECTION: pool_collection
      MONGO_USER: user
      MONGO_PASSWORD: password
      BACKEND_ADDRESS: 0.0.0.0
      BACKEND_PORT: 8000
      BACKEND_VERSION: 1.0.0
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plouf_frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_ADDRESS: backend
      BACKEND_PORT: 8000
      FRONTEND_ADDRESS: 0.0.0.0
      FRONTEND_PORT: 3000
      FRONTEND_VERSION: 1.0.0
    depends_on:
      - backend

volumes:
  mongodb_data:
