version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: plouf_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plouf_backend
    ports:
      - "8000:8000"
    environment:
      MONGO_ADDRESS: mongodb:27017
      MONGO_DATABASE: pool_database
      MONGO_COLLECTION: pool_collection
      MONGO_USER: user
      MONGO_PASSWORD: password
      BACKEND_ADDRESS: 0.0.0.0
      BACKEND_PORT: 8000
    depends_on:
      - mongodb

volumes:
  mongodb_data:
